language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev --python $TRAVIS_PYTHON_VERSION
script:
  - pipenv run make test lint
after_success:
  - codecov
sudo: false
